<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="MagicOnion.Abstractions" Version="6.1.7" />
    <PackageVersion Include="MasterMemory" Version="3.0.4" />
    <PackageVersion Include="MessagePack" Version="3.1.8" />
  </ItemGroup>
</Project>
