<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MagicOnion.Abstractions" Version="6.1.7" />
    <PackageVersion Include="MasterMemory" Version="3.0.4" />
    <PackageVersion Include="MessagePack" Version="3.1.8" />
    <PackageVersion Include="Sirius.Protocol" Version="1.0.0" />
    <PackageVersion Include="Sirius.MasterData" Version="1.0.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>
</Project>