<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sirius.MasterTool</AssemblyName>
    <RootNamespace>Sirius.MasterTool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sirius.Toolbox\Sirius.Toolbox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MagicOnion.Abstractions" />
    <PackageReference Include="MasterMemory" />
    <Reference Include="Sirius.Protocol">
      <HintPath>..\..\lib\Sirius.Protocol.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
