<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Sirius.AssetTool</AssemblyName>
    <RootNamespace>Sirius.AssetTool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sirius.Tooling.Core\Sirius.Tooling.Core.csproj" />
  </ItemGroup>
</Project>
