<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sirius.Toolbox.Tests</RootNamespace>
    <AssemblyName>Sirius.Toolbox.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sirius.Toolbox\Sirius.Toolbox.csproj" />
  </ItemGroup>
</Project>
