<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Sirius.Toolbox</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sirius.MasterData" />
    <PackageReference Include="Sirius.Protocol" />
  </ItemGroup>
</Project>
