<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Sirius.ToolboxUI</AssemblyName>
    <RootNamespace>Sirius.ToolboxUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sirius.Toolbox\Sirius.Toolbox.csproj" />
    <ProjectReference Include="..\..\..\SiriusData\src\Sirius.MasterData\Sirius.MasterData.csproj" />
  </ItemGroup>
</Project>
